# Site
repository: Arib1234/arib1234.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Arib Lokhandwala
title: BTech in AI & Data Science + Cybersecurity (Honours)
email: ariblokhandwala65@gmail.com
phone: 7021187886
website: https://github.com/Arib1234

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: Arib1234
linkedin_username: arib-lokhandwala-0010821b6

# Additional icon links
additional_links:
  - title: GitHub
    icon: fab fa-github
    url: https://github.com/Arib1234
  - title: LinkedIn
    icon: fab fa-linkedin
    url: https://linkedin.com/in/arib-lokhandwala-0010821b6

# About Section
about_profile_image: images/profile.jpg
about_content: |
  I’m Arib Lokhandwala, a solution-driven AI & Data Science engineer with a passion for Cloud Computing, DevOps, Cybersecurity, and Computer Networking. I’ve built cloud-native apps, mobile solutions, and intelligent systems — with hands-on experience in AWS, Azure, and CCNA domains.

  I believe in building practical, scalable, and impactful tech. From AR-based anatomy apps to fake news detectors and financial tracking mobile apps, I strive to blend functionality with innovation.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: AR for Human Anatomy
        quote: >
          Immersive AR learning experience for visualizing human anatomy.
        description: |
          Developed using Unity, Vuforia SDK, and Blender models. Users can view and interact with human organs (Brain, Heart, Skull, etc.) in AR, enhancing medical learning experiences.

      - layout: left
        border: weak
        title: Fake News Detection using Machine Learning
        quote: >
          Detecting misinformation using AI.
        description: |
          Created multiple ML models (Logistic Regression, Random Forest, Gradient Boosting) trained on Kaggle datasets to identify fake vs real news. Useful for social media and journalism sectors.

      - layout: left
        border: weak
        title: Expense Tracker Mobile App
        quote: >
          Personal finance manager with Firebase backend.
        description: |
          Android app with login/signup, expense CRUD, email verification, search-by-date, statistics, and account deletion. Built using Java, Firebase, and Android Studio.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Claidroid Technologies
        sub_title: Intern – Cloud, ML & Android Development
        caption: Dec 2022 – Jan 2023 | Jun 2023 – Jul 2023
        quote: >
          Learned and worked with Azure, ML, OCR & Firebase in a team setting.
        description: |
          Developed OCR-based mobile app using PyTesseract. Worked on cloud deployments using Azure, Firebase integration, and team-based development cycles.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: K J Somaiya Institute of Technology
        sub_title: BTech in AI & Data Science (Honours in Cybersecurity)
        caption: 2021 – Present
        description: |
          GPA: 9.5/10. Studied advanced topics in AI, Cloud, Networking & Security.

      - layout: top-right
        title: Jai Hind College
        sub_title: Class 12 – PCMB
        caption: Completed in 2021
        description: |
          Scored 89.17% in HSC (Science Stream – PCMB)

      - layout: top-right
        title: St. Mary’s High School
        sub_title: Class 10 – SSC
        caption: Completed in 2019
        description: |
          Secured 91.2% (2nd rank in the school)

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: AWS Academy Cloud Foundations
        sub_title: Amazon Web Services
        caption: 2023

      - layout: left
        title: NPTEL – Data Mining (Elite Score)
        sub_title: IIT/NPTEL
        caption: 2024

      - layout: left
        title: Spoken Tutorial – Python
        sub_title: IIT Bombay
        caption: 2023

  - title: A Little More About Me
    layout: text
    content: |
      - 🔐 Familiar with CCNA concepts and networking tools like Wireshark, Packet Tracer, and Nmap.
      - 📱 Experienced in mobile app development using Java & Firebase.
      - ☁️ Passionate about cloud-native development on AWS & Azure.
      - 🏆 3rd Prize winner at KJSIT’s Binary Beat Bounce coding competition.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
